### ISSUE TITLE
Parser cannot parse "go\n"

### ISSUE THREAD

**Issue by UlisseMini** [vampirc/vampirc-uci#9]
```rust
let mut want = Vec::new();
want.push(vampirc_uci::UciMessage::Go {
    time_control: None,
    search_control: None,
});
assert_eq!(vampirc_uci::parse("go\n"), want);

// thread 'main' panicked at 'assertion failed: `(left == right)`
//   left: `[]`,
//  right: `[Go { time_control: None, search_control: None }]`', src/main.rs:10:5

```

**Comment by MadMatt04** [comment]
Wow, for some reason it took me 2 months to notice these tasks that you submitted. Will have a look at this ASAP.

**Comment by MadMatt04** [comment]
I'm not sure just "go" is a valid command. What are the search parameters? I think for search until stop you have to do "go infinite".

**Comment by UlisseMini** [comment]
It worked on stockfish, so I figured it was valid uci.

**Comment by MadMatt04** [comment]
Fair, point, this change has now been made (see #10 ) and will appear in 0.8.3
